import tkinter as tk
from tkinter import ttk
from tkinter.scrolledtext import ScrolledText
import math

from smtp import send_email
from HomebaseScraper.sub.CONSTANTS import *
import HomebaseScraper.lib.HomebaseMain as workers
LARGE_FONT = ("Verdana", 12)


class OliveTree (tk.Tk):
    def __init__(self, *args, **kwargs):
        tk.Tk.__init__(self, *args, **kwargs)
        container = tk.Frame(self)
        self.window_width = 700
        self.window_height = self.get_y_ratio(self.window_width)
        self.geometry("{}x{}".format(self.window_width, self.window_height))
        self.title("Olive Tree Management")

        container.grid(row=0, column=0)
        container.grid_rowconfigure(0, weight=1)
        container.grid_columnconfigure(0, weight=1)

        self.frames = {}

        frame = StartPage(container, self)

        self.frames[StartPage] = frame
        self.nb = ttk.Notebook(self)
        self.page1 = ttk.Frame(self.nb)
        self.page2 = ttk.Frame(self.nb)

        frame.grid(row=0, column=0, sticky="nsew")
        self.show_frame(StartPage)

    @staticmethod
    def get_y_ratio(x_ratio):
        return math.floor(x_ratio * (9/16))

    def show_frame(self, cont):
        frame = self.frames[cont]
        frame.tkraise()

    def tabs(self):
        get_hours = tk.Button(self.page2, text="Fetch worker hours", command=lambda: workers.fetchInfo())
        get_hours.grid(row=1, stick=tk.W+tk.E)

        self.nb.add(self.page1, text="Weekly Tips")
        self.nb.add(self.page2, text="Bimonthly Payment")
        self.nb.grid(row=0)

    def add_elements(self):
        pass


class StartPage(tk.Frame):
    def __init__(self, parent, controller):
        tk.Frame.__init__(self, parent)
        # label = tk.Label(self, text="Start Page", font=LARGE_FONT)
        # label.pack(pady=10, padx=10)


app = OliveTree()
app.tabs()
app.add_elements()
app.mainloop()

"""
send_email(

        send_email(gmail, gmail_password, email_addresses, \
                   'Ali', 'Test!\nGenerated by Python 3.6', [12, 8, 2017])
    ))"""