# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 587)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabPosition(QtWidgets.QTabWidget.North)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDocumentMode(True)
        MainWindow.setTabsClosable(False)
        MainWindow.setMovable(False)
        MainWindow.setTabBarAutoHide(False)
        self.Tab1 = QtWidgets.QWidget()
        self.Tab1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Tab1.setAcceptDrops(False)
        self.Tab1.setObjectName("Tab1")
        self.get_tips = QtWidgets.QPushButton(self.Tab1)
        self.get_tips.setGeometry(QtCore.QRect(40, 450, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.get_tips.setFont(font)
        self.get_tips.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_tips.setMouseTracking(True)
        self.get_tips.setDefault(False)
        self.get_tips.setFlat(False)
        self.get_tips.setObjectName("get_tips")
        self.label = QtWidgets.QLabel(self.Tab1)
        self.label.setGeometry(QtCore.QRect(150, 30, 111, 21))
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Tab1)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 310, 81, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Tab1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(130, 300, 241, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dinein_text = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.dinein_text.setObjectName("dinein_text")
        self.verticalLayout_3.addWidget(self.dinein_text)
        self.togo_text = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.togo_text.setObjectName("togo_text")
        self.verticalLayout_3.addWidget(self.togo_text)
        self.tips_calendar = QtWidgets.QCalendarWidget(self.Tab1)
        self.tips_calendar.setEnabled(True)
        self.tips_calendar.setGeometry(QtCore.QRect(40, 60, 331, 211))
        self.tips_calendar.setFirstDayOfWeek(QtCore.Qt.Sunday)
        self.tips_calendar.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.tips_calendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.tips_calendar.setDateEditEnabled(True)
        self.tips_calendar.setObjectName("tips_calendar")
        self.tips_output = QtWidgets.QTextBrowser(self.Tab1)
        self.tips_output.setGeometry(QtCore.QRect(400, 60, 261, 451))
        self.tips_output.setObjectName("tips_output")
        MainWindow.addTab(self.Tab1, "")
        self.Tab2 = QtWidgets.QWidget()
        self.Tab2.setObjectName("Tab2")
        self.getHours = QtWidgets.QPushButton(self.Tab2)
        self.getHours.setGeometry(QtCore.QRect(50, 440, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.getHours.setFont(font)
        self.getHours.setObjectName("getHours")
        self.frame = QtWidgets.QFrame(self.Tab2)
        self.frame.setGeometry(QtCore.QRect(0, 0, 721, 571))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.chrome_freeze_frame = QtWidgets.QLabel(self.frame)
        self.chrome_freeze_frame.setGeometry(QtCore.QRect(-10, 0, 731, 571))
        self.chrome_freeze_frame.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(90)
        font.setUnderline(False)
        self.chrome_freeze_frame.setFont(font)
        self.chrome_freeze_frame.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.chrome_freeze_frame.setAcceptDrops(False)
        self.chrome_freeze_frame.setToolTip("")
        self.chrome_freeze_frame.setAutoFillBackground(False)
        self.chrome_freeze_frame.setStyleSheet("background: rgb(219, 240, 27);\n"
                                    "")
        self.chrome_freeze_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chrome_freeze_frame.setScaledContents(False)
        self.chrome_freeze_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.chrome_freeze_frame.setWordWrap(True)
        self.chrome_freeze_frame.setOpenExternalLinks(False)
        self.chrome_freeze_frame.setObjectName("chrome_freeze_frame")
        MainWindow.addTab(self.Tab2, "")

        self.retranslateUi(MainWindow)
        MainWindow.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Olive Tree Management"))
        self.get_tips.setText(_translate("MainWindow", "Calculate Employee Tips"))
        self.label.setText(_translate("MainWindow", "Select Today\'s Date"))
        self.label_3.setText(_translate("MainWindow", "Dine-In"))
        self.label_2.setText(_translate("MainWindow", "To - Go"))
        MainWindow.setTabText(MainWindow.indexOf(self.Tab1), _translate("MainWindow", "Weekly Employee Tips"))
        self.getHours.setText(_translate("MainWindow", "Fetch Employee Hour Information"))
        self.chrome_freeze_frame.setText(_translate("MainWindow", "Chrome is running"))
        MainWindow.setTabText(MainWindow.indexOf(self.Tab2), _translate("MainWindow", "Salary Payment"))

